# Generated by Django 5.2.3 on 2026-01-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0003_gameround_question_response_shareevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
