# Generated by Django 5.2.3 on 2026-01-20 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0004_rename_hackathon_o_identif_9df67f_idx_hackathon_o_identif_991a6d_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='otpchallenge',
            new_name='hackathon_o_identif_991a6d_idx',
            old_name='hackathon_o_identif_9df67f_idx',
        ),
    ]
