# Generated by Django 5.2.3 on 2026-01-29 12:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0005_rename_hackathon_o_identif_9df67f_idx_hackathon_o_identif_991a6d_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WordCloud',
            fields=[
                ('word', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('freq', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'wordcloud',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnswerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('question_id', models.IntegerField()),
                ('answer', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('questions', models.JSONField(default=list)),
                ('current_question_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoundScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'hackathon_useranswer',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50, unique=True)),
                ('frequency', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='WordCloudResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('count', models.IntegerField(default=1)),
                ('player_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WordCloudRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(default=1)),
                ('share_token', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('status', models.CharField(default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WordFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
                ('freq', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='WordFrequencyByRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='', max_length=100)),
                ('frequency', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'managed': False},
        ),
        migrations.RemoveConstraint(
            model_name='appusermember',
            name='uniq_member_phone_per_team',
        ),
        migrations.RemoveIndex(
            model_name='appusermember',
            name='hackathon_a_user_id_b12360_idx',
        ),
        migrations.RemoveIndex(
            model_name='authsession',
            name='hackathon_a_user_id_9809eb_idx',
        ),
        migrations.RemoveIndex(
            model_name='authsession',
            name='hackathon_a_member__b32262_idx',
        ),
        migrations.RemoveIndex(
            model_name='otpchallenge',
            name='hackathon_o_identif_991a6d_idx',
        ),
        migrations.RemoveIndex(
            model_name='otpchallenge',
            name='hackathon_o_member__3c5c05_idx',
        ),
        migrations.RemoveIndex(
            model_name='otpchallenge',
            name='hackathon_o_expires_3a37f9_idx',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='shareevent',
            old_name='shared_at',
            new_name='created_at',
        ),
        migrations.AlterUniqueTogether(
            name='response',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='password_hash_b64',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='password_iterations',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='password_salt_b64',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='points',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='team_no',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='username',
        ),
        migrations.RemoveField(
            model_name='appusermember',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='appusermember',
            name='member_id',
        ),
        migrations.RemoveField(
            model_name='appusermember',
            name='name',
        ),
        migrations.RemoveField(
            model_name='appusermember',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='appusermember',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='gameround',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='hackathon',
            name='name',
        ),
        migrations.RemoveField(
            model_name='hackathon',
            name='registration_deadline',
        ),
        migrations.RemoveField(
            model_name='hackathon',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='otpchallenge',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='otpchallenge',
            name='member',
        ),
        migrations.AddField(
            model_name='appuser',
            name='display_name',
            field=models.CharField(default='User', max_length=255),
        ),
        migrations.AddField(
            model_name='appuser',
            name='identifier',
            field=models.CharField(default='user', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='password_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appusermember',
            name='member_name',
            field=models.CharField(default='Member', max_length=255),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='title',
            field=models.CharField(default='Hackathon', max_length=255),
        ),
        migrations.AddField(
            model_name='otpchallenge',
            name='code',
            field=models.CharField(default='000000', max_length=10),
        ),
        migrations.AddField(
            model_name='otpchallenge',
            name='phone',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AddField(
            model_name='shareevent',
            name='event_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='project_name',
            field=models.CharField(default='Project', max_length=255),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='appusermember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='authsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='authsession',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='authsession',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hackathon.appusermember'),
        ),
        migrations.AlterField(
            model_name='authsession',
            name='token_hash',
            field=models.CharField(default='token', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='authsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathon.appuser'),
        ),
        migrations.AlterField(
            model_name='gameround',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='gameround',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hackathon.appuser'),
        ),
        migrations.AlterField(
            model_name='gameround',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathon.question'),
        ),
        migrations.AlterField(
            model_name='gameround',
            name='share_token',
            field=models.CharField(default='token', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='gameround',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otpchallenge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='otpchallenge',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='player_id',
            field=models.CharField(default='player', max_length=255),
        ),
        migrations.AlterField(
            model_name='response',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathon.gameround'),
        ),
        migrations.AlterField(
            model_name='response',
            name='word',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='shareevent',
            name='player_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shareevent',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hackathon.gameround'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='demo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='submission',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='hackathon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathon.hackathon'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathon.appuser'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathon.question'),
        ),
        migrations.AddField(
            model_name='wordcloudresponse',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathon.wordcloudround'),
        ),
        migrations.AddField(
            model_name='wordcloudresponse',
            name='word_cloud_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='hackathon.wordcloudround'),
        ),
        migrations.AddField(
            model_name='roundscore',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathon.wordcloudround'),
        ),
        migrations.AddField(
            model_name='wordfrequencybyround',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathon.wordcloudround'),
        ),
        migrations.RemoveField(
            model_name='submission',
            name='title',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='updated_at',
        ),
    ]
