# Generated by Django 5.2.3 on 2026-01-29 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0006_wordcloud_answerevent_gamesession_roundscore_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='question',
            table='questions',
        ),
        migrations.AlterModelTable(
            name='roundscore',
            table='hackathon_roundscore_v2',
        ),
        migrations.AlterModelTable(
            name='word',
            table='hackathon_word_v2',
        ),
    ]
